# Production function and markup estimation in R
# This script replicates the Stata routines located in
# "Ancillary codes/Codes_Germany/Codes_Data_German_manufacturing/Codes"
# for estimating translog production functions and computing markups.

# Load project configuration
source(paste0(dirname(rstudioapi::getActiveDocumentContext()$path), "/Main.R"))

# -----------------------------------------------------------------------------
# 1. Load data ---------------------------------------------------------------
# -----------------------------------------------------------------------------
# The script expects that the data created in earlier steps of the project are
# available in the working directory.  In particular we require:
#   - "sbs_br_combined.RDS" : firm-level accounting data
#   - "product_data_10_digit_all_prodfra_.RDS" : product-level data used to
#       construct firm price indices
# These files are generated by the earlier scripts in the project (code a.).

library(data.table)
library(fixest)
library(AER)

firm_data <- readRDS("sbs_br_combined.RDS")
firm_data <- firm_data[year > 2009]

product_data <- readRDS("product_data_10_digit_all_prodfra_.RDS")
product_summary <- readRDS("product_firm_data_pre_high_growth.RDS")
deflators <- fread("Ancillary datasets/deflators.csv")
setDT(product_data)
setkey(product_data, firmid, prodfra_plus, year)

# -----------------------------------------------------------------------------
# 2. Construct firm price indices -------------------------------------------
# -----------------------------------------------------------------------------
# Following the approach in the Stata code, we construct firm-level price indices
product_data <- product_data[, price := rev / sold_q] %>%
  .[, ln_price := fifelse(price > 0, log(price), NA_real_)]  %>%
  .[, ln_growth_p:=ln_price-shift(ln_price), by=.(firmid, prodfra_plus)] %>%
  .[, s_unr := rev / sum(rev, na.rm = TRUE), by = .(firmid, year)] %>% 
  .[, s_unr_lag := shift(s_unr), by = .(firmid, prodfra_plus)] %>%
  .[, s_weight_unr := (s_unr + s_unr_lag) / 2] %>%
  .[is.na(s_weight_unr) | is.infinite(s_weight_unr), s_weight_unr := 0]

# Compute firm-level price changes
firm_index <- product_data[!is.na(ln_growth_p), .(
  delta_p_unr = sum(s_weight_unr * ln_growth_p, na.rm = TRUE),
  total_weight = sum(s_unr, na.rm = TRUE),
  valid = sum(s_unr, na.rm = TRUE) >= 0.95
), by = .(firmid, year)] %>% 
  merge(firm_data[, c("firmid", "year","NACE_BR")], 
        all.x=T, by=c("firmid", "year")) %>%
  setorder(firmid, year) %>%
  .[valid == FALSE , delta_p_unr := 0] %>%
  .[is.infinite(delta_p_unr) | is.na(delta_p_unr) | is.nan(delta_p_unr), delta_p_unr := NA_real_]

# Construct industry-year price index to impute missing firm indices
industry_index <- firm_index[valid==T, .(delta_p_unr_NACE_BR=mean(delta_p_unr, na.rm=T)), by=.(NACE_BR, year)] %>%
  rbind(data.table(year=2009, delta_p_unr_NACE_BR=100, NACE_BR=unique(.[,NACE_BR])), fill=T) %>%
  setorder(NACE_BR, year) %>% .[, P_index_ln_NACE_BR := cumsum(delta_p_unr_NACE_BR), by = NACE_BR]

# Merge industry index to firm index
firm_index <- merge(firm_index, industry_index, by=c("NACE_BR", "year"), all.x = T) 

# Make the complete panel for firm_index
firm_index <- merge(CJ(firmid = unique(firm_index$firmid), year = 2009:2021), firm_index, by = c("firmid", "year"), all.x = TRUE) %>%
  # Fill in missing industry codes
  .[year==2009, delta_p_unr := 0] %>%
  .[, P_index_ln := cumsum(delta_p_unr), by = firmid] %>%
  # Impute missing firm price indices with averages 
  # (e.g if year 2015 is missing then use the average between year 2014 and 2016 or the closest available year)
  .[is.na(delta_p_unr), `:=`(delta_p_unr = delta_p_unr_NACE_BR,
                             impute_flag=1), by = firmid] %>%
  .[, test_delta_p_unr := (na.locf(delta_p_unr, na.rm = FALSE)+na.locf(delta_p_unr, na.rm = FALSE, fromLast=T))/2, by = firmid] %>%
  .[year==2009, test_delta_p_unr := 100] %>%
  .[, P_index_ln := cumsum(test_delta_p_unr), by = firmid]

firm_price_index <- firm_index[, .(firmid, year, pf = P_index_ln)]

# -----------------------------------------------------------------------------
# 3. Construct market share variables -------------------------------------------
# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------


# 1. product-level market sales
product_data[, market_sales := sum(rev, na.rm = TRUE),
             by = .(prodfra_plus, year)]

# 2. firm’s product market share
product_data[, ms_firmproduct := rev / market_sales]

# 3. firm total revenue for weights
product_data[, firmsales := sum(rev, na.rm = TRUE), by = .(firmid, year)]

# 4. firm-level market share
firm_ms <- product_data[
  , .(Firm_ms = sum(ms_firmproduct * rev / firmsales, na.rm = TRUE)),
  by = .(firmid, year)
]
firm_ms[, Firm_ms := 100 * Firm_ms]          
firm_ms[, Rshare := log(Firm_ms)]            

# -----------------------------------------------------------------------------
# 4. Prepare production variables -------------------------------------------
# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
df <- merge(product_summary, firm_price_index, by = c("firmid", "year"), all.x = TRUE) %>%
  merge(firm_ms, by = c("firmid", "year"), all.x = TRUE)

setDT(df)
df <- df[order(firmid, year)]

# Log variables and cost shares
small <- 0

df[, `:=`(
  ln_Y = log(nq + small),
  ln_K = log(capital + small),
  ln_L = log(empl + small),
  ln_M = log(raw_materials + small),
  ln_wage = log(labor_cost / empl)
  # Rshare = log(raw_materials / nq + small)
)] %>%
  .[, pf:=log(pf) - ln_wage]

# Lagged materials (to be used as proxy for unobserved productivity)
df[, ln_P:= shift(ln_M), by = firmid] 

# Higher order and interaction terms
df[, `:=`(
  ln_L2 = ln_L^2,
  ln_K2 = ln_K^2,
  ln_M2 = ln_M^2,
  ln_L_K = ln_L * ln_K,
  ln_L_M = ln_L * ln_M,
  ln_K_M = ln_K * ln_M,
  ln_L_K_M = ln_L * ln_K * ln_M,
  # Cubic and mixed third-order terms
  ln_L3 = ln_L^3,
  ln_K3 = ln_K^3,
  ln_M3 = ln_M^3,
  ln_L_K2 = ln_L * ln_K^2,
  ln_L_M2 = ln_L * ln_M^2,
  ln_K_M2 = ln_K * ln_M^2,
  ln_L2_K = ln_L^2 * ln_K,
  ln_L2_M = ln_L^2 * ln_M,
  ln_K2_M = ln_K^2 * ln_M
  # ln_L2_K_M = ln_L^2 * ln_K * ln_M,
  # ln_L_K2_M = ln_L * ln_K^2 * ln_M,
  # ln_L_K_M2 = ln_L * ln_K * ln_M^2
)]

df[, `:=`(
  ln_P2 = ln_P^2,
  ln_L_P = ln_L * ln_P,
  ln_K_P = ln_K * ln_P,
  ln_L_K_P = ln_L * ln_K * ln_P,
  ln_P3 = ln_P^3,
  ln_L_K2 = ln_L * ln_K^2,
  ln_L_P2 = ln_L * ln_P^2,
  ln_K_P2 = ln_K * ln_P^2,
  ln_L2_P = ln_L^2 * ln_P,
  ln_K2_P = ln_K^2 * ln_P
)]


# Price interaction terms
df[, `:=`(
  priceL   = pf * ln_L,
  priceK   = pf * ln_K,
  priceM   = pf * ln_M,
  priceL2  = pf * ln_L2,
  priceK2  = pf * ln_K2,
  priceM2  = pf * ln_M2,
  priceLM  = pf * ln_L * ln_M,
  priceLK  = pf * ln_L * ln_K,
  priceMK  = pf * ln_M * ln_K,
  priceLMK = pf * ln_L * ln_M * ln_K,
  priceL3  = pf * ln_L3,
  priceK3  = pf * ln_K3,
  priceM3  = pf * ln_M3,
  priceLK2 = pf * ln_L_K2,
  priceLM2 = pf * ln_L_M2,
  priceKM2 = pf * ln_K_M2,
  priceL2K = pf * ln_L2_K,
  priceL2M = pf * ln_L2_M,
  priceK2M = pf * ln_K2_M
  # priceL2KM = pf * ln_L2_K_M,
  # priceLK2M = pf * ln_L_K2_M,
  # priceLKM2 = pf * ln_L_K_M2
)]

# Lagged instruments
lag_vars <- c("ln_L", "ln_L2", "ln_L3", "ln_K", "ln_K2", "ln_K3", "ln_L_K", "ln_L_K2", "ln_L2_K",
              "ln_P", "ln_P2","ln_L_P","ln_K_P","ln_L_K_P","ln_P3", "ln_L_K2",
              "ln_L_P2","ln_K_P2", "ln_L2_P", "ln_K2_P","ln_M", "ln_M2", "ln_M3", "ln_K_M", "ln_L_M", "ln_K_M2",
              "ln_L2_M", "ln_L_M2", "ln_K2_M", "ln_L_K_M",
              "log_n_products", "ln_wage",
              "pf", "Rshare",
              "priceL", "priceK", "priceM",
              "priceL2", "priceK2", "priceM2",
              "priceL3", "priceK3", "priceM3",
              "priceLM", "priceLK", "priceMK", "priceLMK",
              "priceLK2", "priceLM2", "priceKM2",
              "priceL2K", "priceL2M", "priceK2M")

for (v in lag_vars) {
  print(v)
  df[, paste0("l_", v) := shift(get(v)), by = firmid]
}

# -----------------------------------------------------------------------------
# 4. Estimate production function (IV) --------------------------------------
# -----------------------------------------------------------------------------
# The specification mirrors the Stata implementation using a translog
# production function with materials treated as an endogenous input.

iv_formula <- as.formula(ln_Y ~ ln_L + ln_K + ln_L2 + ln_K2 + ln_L_K +
                           l_log_n_products + l_ln_wage +
                           l_ln_L + l_ln_L2 + l_ln_L3 + 
                           l_ln_L_K2 + l_ln_L_P2 + l_ln_L_K + l_ln_L_P +
                           l_ln_L2_K + l_ln_L2_P + 
                           l_ln_K + l_ln_K2 + l_ln_K3 + 
                           l_ln_K_P2 + l_ln_K_P + l_ln_K2_M + 
                           l_ln_P + l_ln_P2 + l_ln_P3 +
                           l_ln_L_K_P + 
                           ln_M + ln_M2 + ln_K_M + ln_L_M + ln_L_K_M + 
                           pf + Rshare +
                           priceL + priceK + priceM +
                           priceL2 + priceK2 + priceM2 +
                           priceLM + priceLK + priceMK + priceLMK |
                           ln_L + ln_K + ln_L2 + ln_K2 + ln_L_K +
                           l_log_n_products + l_ln_wage +
                           l_ln_L + l_ln_L2 + l_ln_L3 + 
                           l_ln_L_K2 + l_ln_L_P2 + l_ln_L_K + l_ln_L_P +
                           l_ln_L2_K + l_ln_L2_P + 
                           l_ln_K + l_ln_K2 + l_ln_K3 + 
                           l_ln_K_P2 + l_ln_K_P + l_ln_K2_M + 
                           l_ln_P + l_ln_P2 + l_ln_P3 +
                           l_ln_L_K_P +
                           l_ln_M + l_ln_M2 + l_ln_K_M + l_ln_L_M + l_ln_L_K_M +
                           l_pf + l_Rshare +
                           l_priceL + l_priceK + l_priceM +
                           l_priceL2 + l_priceK2 + l_priceM2 +
                           l_priceLM + l_priceLK + l_priceMK + l_priceLMK)

iv_vars <- all.vars(iv_formula)
reg_data <- df[complete.cases(df[, ..iv_vars])]

# Include industry and year fixed effects using factor variables
reg_data[, `:=`(industry = factor(NACE_BR), year_fe = factor(year))]
reg_data<-reg_data[, .SD, .SDcols = c("firmid", "industry", "year_fe", "number_of_products", iv_vars)]

for(industry_temp in unique(reg_data$industry)){
  industry_temp="2830"
  pf_model <- ivreg(ln_Y ~ ln_L + ln_K + ln_L2 + ln_K2 + ln_L_K +
                      l_log_n_products + l_ln_wage +
                      l_ln_L + l_ln_L2 + l_ln_L3 + 
                      l_ln_L_K2 + l_ln_L_P2 + l_ln_L_K + l_ln_L_P +
                      l_ln_L2_K + l_ln_L2_P + 
                      l_ln_K + l_ln_K2 + l_ln_K3 + 
                      l_ln_K_P2 + l_ln_K_P + l_ln_K2_M + 
                      l_ln_P + l_ln_P2 + l_ln_P3 +
                      l_ln_L_K_P + 
                      ln_M + ln_M2 + ln_K_M + ln_L_M + ln_L_K_M + 
                      pf + Rshare +
                      priceL + priceK + priceM +
                      priceL2 + priceK2 + priceM2 +
                      priceLM + priceLK + priceMK + priceLMK |
                      ln_L + ln_K + ln_L2 + ln_K2 + ln_L_K +
                      l_log_n_products + l_ln_wage +
                      l_ln_L + l_ln_L2 + l_ln_L3 + 
                      l_ln_L_K2 + l_ln_L_P2 + l_ln_L_K + l_ln_L_P +
                      l_ln_L2_K + l_ln_L2_P + 
                      l_ln_K + l_ln_K2 + l_ln_K3 + 
                      l_ln_K_P2 + l_ln_K_P + l_ln_K2_M + 
                      l_ln_P + l_ln_P2 + l_ln_P3 +
                      l_ln_L_K_P +
                      l_ln_M + l_ln_M2 + l_ln_K_M + l_ln_L_M + l_ln_L_K_M +
                      l_pf + l_Rshare +
                      l_priceL + l_priceK + l_priceM +
                      l_priceL2 + l_priceK2 + l_priceM2 +
                      l_priceLM + l_priceLK + l_priceMK + l_priceLMK, data = reg_data[industry == industry_temp])
  pf_model_alt <- feols(ln_Y ~ ln_L + ln_K + ln_L2 + ln_K2 + ln_L_K +
                          l_log_n_products + l_ln_wage +
                          l_ln_L + l_ln_L2 + l_ln_L3 + 
                          l_ln_L_K2 + l_ln_L_P2 + l_ln_L_K + l_ln_L_P +
                          l_ln_L2_K + l_ln_L2_P + 
                          l_ln_K + l_ln_K2 + l_ln_K3 + 
                          l_ln_K_P2 + l_ln_K_P + l_ln_K2_M + 
                          l_ln_P + l_ln_P2 + l_ln_P3 +
                          l_ln_L_K_P + 
                          ln_M + ln_M2 + ln_K_M + ln_L_M + ln_L_K_M + 
                          pf + Rshare +
                          priceL + priceK + priceM +
                          priceL2 + priceK2 + priceM2 +
                          priceLM + priceLK + priceMK + priceLMK , 
                        iv = ~ ln_M + ln_M2 + ln_K_M + ln_L_M + ln_L_K_M + 
                          pf + Rshare +
                          priceL + priceK + priceM +
                          priceL2 + priceK2 + priceM2 +
                          priceLM + priceLK + priceMK + priceLMK ~  
                          l_ln_M + l_ln_M2 + l_ln_K_M + l_ln_L_M + l_ln_L_K_M +
                          l_pf + l_Rshare +
                          l_priceL + l_priceK + l_priceM +
                          l_priceL2 + l_priceK2 + l_priceM2 +
                          l_priceLM + l_priceLK + l_priceMK + l_priceLMK,
                        data=reg_data[industry == industry_temp])
  
  ci <- coef(pf_model)
  cf <- coef(pf_model_alt)
  all.equal(cf[names(ci)], ci[names(cf)], tolerance = 1e-8)
  
  # Compare fitted values on the common estimation sample
  s <- rownames(model.frame(pf_model))
  all.equal(predict(pf_model)[s], predict(pf_model_alt)[s], tolerance = 1e-8)
  
  
}